### ISSUE TITLE
Latest release (0.4.0) requires Django<=1.7

### ISSUE THREAD

**Issue by randuhmm** [nephila/djangocms-highlightjs#4]
Hello, I want to use this package with Django 1.8 the latest development build seems to support 1.8 but the most recent release requires <=1.7. I am planning on fixing this on my fork by adding a new release from the development branch. Let me know what you think!

**Comment by randuhmm** [comment]
@yakky thanks for the quick response, I apologize in advance for my lack of knowledge in GitHub etiquette, I am fairly new to reporting and issue tracking here.

Here are my steps to reproduce this issue:

- Use pip (or PyPI) to install a version of Django >= 1.7
- Use pip (or PyPI) to install djangocms-highlightjs
- You should see the 1.8 version of Django uninstalled and a 1.6 version installed

If you download and extract the package you will see that `django<1.7` is specified in `setup.py`. I believe that you have removed this in newer commits, however the version on PyPI is the 0.4.0 release which has the dependency on <1.7.

![image](https://cloud.githubusercontent.com/assets/23922/14216112/d61041e8-f7fb-11e5-8802-4e9b6e6b0cca.png)

I also had some issues with the latest development branch and python 2.7 but perhaps that belongs in a separate issue. Thanks again!

**Comment by yakky** [comment]
@randuhmm it's totally my fault!
I never release a compatible version: repository it's ready for release but I've not released yet, how dumb of me.
A release will be ready soon. In the meantime you can just ``pip install https://github.com/nephila/djangocms-highlightjs/archive/develop.zip``
If you can check that install from github works, I'll release 0.5.0 soon
You have to reinstall the correct django version as in develop I dropped the dependency on django, as it's quite stupid anyway
And thanks for your detailed report!

**Comment by randuhmm** [comment]
No problem, I am glad I could help. Also, I already tested out the latest code in the develop branch and I found one small issue with installing the package, it seems that the `from __future__ import unicode_literals` import in `setup.py` is causing issues with distutils for python 2.7.X. I patched this in my fork so I will submit a PR for it as well.

**Comment by yakky** [comment]
@randuhmm I merged your patch, but then I ended up solving in a slighltly different way.
I also update the test matrix to a more updated layout
I'll release all this soonish

**Comment by yakky** [comment]
@randuhmm sorry, 0.5.0 has been delayed for no good reason.
Released now. Thanks for reporting this

**Comment by randuhmm** [comment]
Thanks @yakky, you rock!
